### PR TITLE
Added & updated keybinds

### PR DESCRIPTION
**Pull request by Z3r0Tw0-ZT**
Hi @adi1090x , I have added keybinds for hyprland and I have updated bspwm keybinds

### CODE REVIEW

**Comment by Z3r0Tw0-ZT** [comment]
Sorry for the close and reopening. This is my first contribution

**Comment by Z3r0Tw0-ZT** [comment]
Added keybinds for Qtile

**Comment by adi1090x** [comment]
Hey @Z3r0Tw0-ZT Check this. The PR is failing in some checks, Fix it.

Screenshot_2024-01-08-15-38-33_1920x1080

**Comment by Z3r0Tw0-ZT** [comment]
Hi @adi1090x , fixed the package issue

**Comment by adi1090x** [comment]
merged.

**Pull request merged**
